/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.stud798179.exp1;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  public void testConvertInchesToMeters() {
    double result = App.convert(1, "in", "m");
    assertEquals(0.0254, result);
  }

  @Test
  public void testConvertFeetToMeters() {
    double result = App.convert(1, "ft", "m");
    assertEquals(0.3048, result);
  }

  @Test
  public void testConvertMilesToMeters() {
    double result = App.convert(1, "mi", "m");
    assertEquals(1609.344, result);
  }

  @Test
  public void testConvertMetersToInches() {
    double result = App.convert(1, "m", "in");
    assertEquals(39.37007874015748, result);
  }

  @Test
  public void testConvertMetersToFeet() {
    double result = App.convert(1, "m", "ft");
    assertEquals(3.280839895013123, result);
  }

  @Test
  public void testConvertMetersToMiles() {
    double result = App.convert(1000, "m", "mi");
    assertEquals(0.621371192237334, result);
  }
}
